<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'content_type.article' => 'f5045daed922b83f5a10b6063e58c94bb1c1296f',
  'content_type.webform' => '946b7c248f7fcacde5a66cc5fa15af717a702000',
  'field.node.body.article' => '2b3c96afc9203d9e36ffdefd5b51cad684478a15',
  'field.node.field_article_image.article' => '12e2ad1a9c0aa4c83b6cf2189a82985b1db43f78',
  'permission.create_article_content' => '781677febc1cffa40486b5c612eee5cce22ca014',
  'permission.create_webform_content' => '132fbfa207552dbe945039552f832b1259192572',
  'permission.delete_any_article_content' => '16e28947bc352a81883575b3f0ef71f063a2c8ce',
  'permission.delete_any_webform_content' => '0dcb06777d00599bb36f3376f3adf4defddbe113',
  'permission.delete_own_article_content' => '7b8bb7ef7355db6c434288b423b3ceb192a8a816',
  'permission.delete_own_webform_content' => '581011b223f22e9c9e8a0e3a8565797c535b14b0',
  'permission.edit_any_article_content' => '1e0b88efa3e696b1229f554188383c0f6e1c4118',
  'permission.edit_any_webform_content' => '2f951f5a76624f656c2643d3da0c5b62ad6da57c',
  'permission.edit_own_article_content' => '49eb3e97c98b7a022f0a0dbbd25f29720014d2c8',
  'permission.edit_own_webform_content' => 'c44e1f12154984934387fcb888e9cffbb74dbaf1',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'node',
  'field_sql_storage',
  'text',
  'image',
);
