<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'content_type.article' => 'f5045daed922b83f5a10b6063e58c94bb1c1296f',
  'content_type.webform' => '946b7c248f7fcacde5a66cc5fa15af717a702000',
  'variable.theme_default' => '832fb3cd69be9f97e9725fae3e63d472e2bb4b25',
  'permission.create_webform_content' => '132fbfa207552dbe945039552f832b1259192572',
  'permission.delete_any_webform_content' => '0dcb06777d00599bb36f3376f3adf4defddbe113',
  'permission.delete_own_webform_content' => '581011b223f22e9c9e8a0e3a8565797c535b14b0',
  'permission.edit_any_webform_content' => '2f951f5a76624f656c2643d3da0c5b62ad6da57c',
  'permission.edit_own_webform_content' => 'c44e1f12154984934387fcb888e9cffbb74dbaf1',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'node',
  'strongarm',
  'ctools',
  'system',
);
